---
- name: Déployer la configuration Traefik depuis le dépôt
  hosts: traefik
  become: yes
  tasks:
    - name: Copier la configuration statique
      copy:
        src: traefik/traefik.yaml
        dest: /etc/traefik/traefik.yaml
        owner: root
        group: root
        mode: '0644'
      notify: restart traefik

    - name: Générer les fichiers de configuration dynamique pour chaque machine
      template:
        src: traefik-service.j2
        dest: "/etc/traefik/conf.d/{{ item }}.yml"
        owner: root
        group: root
        mode: '0644'
      loop: "{{ groups['all'] | difference(['traefik']) }}"
      when:
        - hostvars[item].traefik_domain is defined
        - hostvars[item].traefik_port is defined
      notify: restart traefik

  handlers:
    - name: restart traefik
      systemd:
        name: traefik
        state: restarted
